// Mocks generated by Mockito 5.4.5 from annotations
// in posha/test/cubit/recipe_detail_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:posha/models/category_model.dart' as _i6;
import 'package:posha/models/recipe_model.dart' as _i3;
import 'package:posha/services/api_service.dart' as _i4;
import 'package:posha/services/local_storage_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecipe_1 extends _i1.SmartFake implements _i3.Recipe {
  _FakeRecipe_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  _i5.Future<List<_i3.Recipe>> searchRecipes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRecipes,
          [query],
        ),
        returnValue: _i5.Future<List<_i3.Recipe>>.value(<_i3.Recipe>[]),
      ) as _i5.Future<List<_i3.Recipe>>);

  @override
  _i5.Future<List<_i3.Recipe>> getRecipesByFirstLetter(String? letter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipesByFirstLetter,
          [letter],
        ),
        returnValue: _i5.Future<List<_i3.Recipe>>.value(<_i3.Recipe>[]),
      ) as _i5.Future<List<_i3.Recipe>>);

  @override
  _i5.Future<_i3.Recipe> getRecipeById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getRecipeById,
          [id],
        ),
        returnValue: _i5.Future<_i3.Recipe>.value(_FakeRecipe_1(
          this,
          Invocation.method(
            #getRecipeById,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Recipe>);

  @override
  _i5.Future<List<_i6.Category>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Category>>.value(<_i6.Category>[]),
      ) as _i5.Future<List<_i6.Category>>);

  @override
  _i5.Future<List<String>> getAreas() => (super.noSuchMethod(
        Invocation.method(
          #getAreas,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<List<String>> getIngredients() => (super.noSuchMethod(
        Invocation.method(
          #getIngredients,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<List<_i3.Recipe>> filterByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterByCategory,
          [category],
        ),
        returnValue: _i5.Future<List<_i3.Recipe>>.value(<_i3.Recipe>[]),
      ) as _i5.Future<List<_i3.Recipe>>);

  @override
  _i5.Future<List<_i3.Recipe>> filterByArea(String? area) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterByArea,
          [area],
        ),
        returnValue: _i5.Future<List<_i3.Recipe>>.value(<_i3.Recipe>[]),
      ) as _i5.Future<List<_i3.Recipe>>);

  @override
  _i5.Future<List<_i3.Recipe>> filterByIngredient(String? ingredient) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterByIngredient,
          [ingredient],
        ),
        returnValue: _i5.Future<List<_i3.Recipe>>.value(<_i3.Recipe>[]),
      ) as _i5.Future<List<_i3.Recipe>>);

  @override
  _i5.Future<List<_i3.Recipe>> getAllRecipes() => (super.noSuchMethod(
        Invocation.method(
          #getAllRecipes,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Recipe>>.value(<_i3.Recipe>[]),
      ) as _i5.Future<List<_i3.Recipe>>);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i7.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i3.Recipe> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: <_i3.Recipe>[],
      ) as List<_i3.Recipe>);

  @override
  bool isFavorite(String? id) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [id],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> toggleFavorite(_i3.Recipe? recipe) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [recipe],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
